### ISSUE TITLE
Hey Baby

### ISSUE THREAD

**Issue by ghost** [GTAWWEKID/TIC-TAC-TOE#1]
Remember me Sunshine ?

**Comment by GTAWWEKID** [comment]
If you want to work on a project with me, just hmu. If project is success, payout will be $30,000USD.

**Comment by MrV1rusYT** [comment]
Payout first then I will join you

**Comment by GTAWWEKID** [comment]
0.0016% up-front

**Comment by ghost** [comment]
Suck my dick hoe

**Comment by ghost** [comment]
Just to let you know you have been unbanned from PSXHAX
